### PR TITLE
Update extension.ts

### PR DESCRIPTION
**Pull request by sandroweb**
I need generate `equals`, `toString` and `constructors with fields` separated.

### CODE REVIEW

**Comment by sohibegit** [comment]
what do you need exactly?

**Comment by sohibegit** [comment]
> I need generate `equals`, `toString` and `constructors with fields` separated.

what do you need exactly?

**Comment by sandroweb** [comment]
My VSCode show only this codes:
image

I need `equals`, `toString` and `constructors with fields` separated.

**Comment by sandroweb** [comment]
Sorry! I don't pushed in the "context.subscriptions".

**Comment by sohibegit** [comment]
Can you create a "generate more" option and put whatever you want in it?

**Comment by sandroweb** [comment]
The extension only show me:
- Generate emoty constructor
- Generate constructor using all final fields
- Generate all "Quick"
- Generator GUI

I need include other options:
- Generate emoty constructor
- Generate hasCode and equals
- Generate toString
- Generate constructor using all fields
- Generate constructor using all final fields
- Generate all "Quick"
- Generator GUI

**Comment by sohibegit** [comment]
I know, but the options are a lot to put together, that's why we need an option called "Generate more" that will show another menu with the extras that you want.

**Comment by sohibegit** [comment]
thank you for your support version 7.0.0 fixs your problem

**Pull request closed without merging**
